export const EmotionDropdownOptions = [
  { id: '1', value: 'Afraid', title: 'Afraid' },
  { id: '2', value: 'Angry', title: 'Angry' },
  { id: '3', value: 'Anxious', title: 'Anxious' },
  { id: '4', value: 'Treated-harshly', title: 'Been treated harshly' },
  { id: '5', value: 'Depressed', title: 'Depressed' },
  { id: '6', value: 'Desire', title: 'Desire' },
  { id: '7', value: 'Burdened', title: 'Feeling burdened' },
  { id: '8', value: 'Loser', title: 'Feeling like a loser' },
  { id: '9', value: 'Lonely', title: 'Feeling lonely' },
  { id: '10', value: 'Proud', title: 'Feeling proud' },
  { id: '11', value: 'Underpriviledged', title: 'Feeling underpriviledged' },
  { id: '12', value: 'Weak', title: 'Feeling weak' },
  { id: '13', value: 'Upset', title: 'Feeling upset' },
  { id: '14', value: 'Danger', title: 'In danger' },
  { id: '15', value: 'Lost-hope', title: 'Lost Hope' },
  { id: '16', value: 'Lack-of-faith', title: 'Lack of faith' },
  { id: '17', value: 'Courage', title: 'Need courage' },
  { id: '18', value: 'Not-appreciated', title: 'Not Appreciated' },
  { id: '19', value: 'Direction', title: 'Need direction' },
  {
    id: '20',
    value: 'Overwhelmed-with-hardships',
    title: 'Overwhelmed with harships',
  },
  {
    id: '21',
    value: 'Love-and-tranquility',
    title: 'Seeking love n tranquility',
  },
  { id: '22', value: 'Seeking-peace', title: 'Seeking peace' },
  { id: '23', value: 'Seeking-patience', title: 'Seeking patience' },
  { id: '24', value: 'Stay-steadfast', title: 'Struggling to stay steadfast' },
  { id: '25', value: 'Hard-on-myself', title: 'Too hard on myself' },
  { id: '26', value: 'Unhappy', title: 'Unhappy' },
  { id: '27', value: 'Wishing-friend', title: 'Wishing for a friend' },
];
